spring:
  application:
    name: taco-cloud
  thymeleaf:
    cache: false
  data:
    mongodb:
      host: localhost
      port: 27017
      username: tacocloud
      password: tacocloud
      database: tacoclouddb